# Generated by Django 3.2.7 on 2022-10-15 03:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_gallery_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
