# Generated by Django 4.1.3 on 2022-11-11 05:20

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('retreat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retreat',
            name='excluded',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='retreat',
            name='included',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='retreat',
            name='know_before_you_go',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
