# Generated by Django 4.1.3 on 2022-11-14 10:27

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('retreat', '0002_retreat_excluded_retreat_included_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retreat',
            name='day_1',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='retreat',
            name='day_10',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='retreat',
            name='day_2',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='retreat',
            name='day_3',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='retreat',
            name='day_4',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='retreat',
            name='day_5',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='retreat',
            name='day_6',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='retreat',
            name='day_7',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='retreat',
            name='day_8',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='retreat',
            name='day_9',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
