# Generated by Django 4.1.3 on 2022-11-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retreat', '0003_retreat_day_1_retreat_day_10_retreat_day_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retreat',
            name='day_1',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
