# Generated by Django 3.2.7 on 2022-10-17 04:27

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('body', tinymce.models.HTMLField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('img', models.ImageField(null=True, upload_to='img')),
                ('duration', models.DurationField()),
                ('language', models.CharField(choices=[('ENG', 'English'), ('HIN', 'Hindi')], max_length=100)),
            ],
        ),
    ]
