# Generated by Django 3.2.7 on 2022-10-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='discounted_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Experienced-Beginner', 'Experienced-Beginner'), ('Experienced', 'Experienced'), ('Intermediate', 'Intermediate'), ('Intermediate-Advanced', 'Intermediate-Advanced'), ('Advanced', 'Advanced')], default='BEG', max_length=100),
        ),
        migrations.AddField(
            model_name='courses',
            name='price',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='courses',
            name='style',
            field=models.CharField(choices=[('Ashtanga Vinyasa-style', 'Ashtanga Vinyasa-style')], default='AVS', max_length=100),
        ),
        migrations.AlterField(
            model_name='courses',
            name='date_added',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='courses',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi')], default='ENG', max_length=100),
        ),
    ]
