# Generated by Django 3.2.7 on 2022-10-21 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homeslider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeslider',
            name='imagename',
        ),
    ]
