# Generated by Django 3.2.7 on 2022-10-21 03:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_homeslider_imagename'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslider',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
