# Generated by Django 3.2.7 on 2022-10-21 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homeslider_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=25)),
                ('message', models.TextField(max_length=100)),
                ('img', models.ImageField(null=True, upload_to='img')),
            ],
        ),
    ]
