# Generated by Django 3.2.7 on 2022-10-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='message',
            field=models.TextField(),
        ),
    ]
