# Generated by Django 3.2.7 on 2022-10-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_ourteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourteam',
            name='facebook_link',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='ourteam',
            name='instagram_link',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='ourteam',
            name='twitter_link',
            field=models.URLField(default=''),
        ),
    ]
