# Generated by Django 3.2.7 on 2022-10-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20221021_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourteam',
            name='facebook_link',
            field=models.URLField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='instagram_link',
            field=models.URLField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='twitter_link',
            field=models.URLField(default='', null=True),
        ),
    ]
