# Generated by Django 3.2.7 on 2022-10-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_ourteam_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourteam',
            name='position',
            field=models.CharField(max_length=100),
        ),
    ]
