# Generated by Django 3.2.7 on 2022-10-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_ourteam_twitter_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourteam',
            name='facebook_link',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='instagram_link',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
