# Generated by Django 3.2.7 on 2022-10-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20221021_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='testimonials')),
                ('spoken_words', models.TextField()),
            ],
        ),
    ]
