# Generated by Django 3.2.7 on 2022-11-01 02:59

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('highlight', tinymce.models.HTMLField()),
                ('body', tinymce.models.HTMLField()),
                ('date_added', models.DateField()),
                ('img', models.ImageField(null=True, upload_to='img')),
                ('price', models.IntegerField(default=1)),
                ('discounted_price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('sn', models.AutoField(primary_key=True, serialize=False)),
                ('review', models.TextField(max_length=500)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('name', models.TextField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('rating', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
    ]
