# Generated by Django 3.2.7 on 2022-11-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.TextField(max_length=100),
        ),
    ]
