# Generated by Django 3.2.7 on 2022-10-07 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog__app', '0004_alter_blog_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
