# Generated by Django 3.2.7 on 2022-10-12 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog__app', '0007_alter_blog_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('sn', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(max_length=500)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('author', models.TextField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog__app.blog')),
            ],
        ),
    ]
